import { supabase } from './supabase';
import { AppSettings, Category, FinancialCard, InstallmentPlan, MonthlyBudget, NetWorthSnapshot, PatrimonyItem, Transaction } from '../types';
import { enqueuePendingSupabaseSync } from './supabaseSyncQueue';
const TRANSACTIONS_STORAGE_KEY='mis_gastos_transactions_v1';
const CARDS_STORAGE_KEY='cream_financial_cards_v1';
const INSTALLMENTS_STORAGE_KEY='cream_installment_plans_v1';
export interface SupabaseDataPayload{transactions:Transaction[];categories:Category[];budgets:MonthlyBudget[];settings:AppSettings|null;patrimonyItems:PatrimonyItem[];netWorthSnapshots:NetWorthSnapshot[];cards:FinancialCard[];installmentPlans:InstallmentPlan[];}
function readLocalTransactions():Transaction[]{if(typeof window==='undefined')return[];try{const raw=window.localStorage.getItem(TRANSACTIONS_STORAGE_KEY);if(!raw)return[];const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function readLocalArray<T>(key:string):T[]{if(typeof window==='undefined')return[];try{const raw=window.localStorage.getItem(key);if(!raw)return[];const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function mergeTransactions(cloudTransactions:Transaction[]):Transaction[]{const localTransactions=readLocalTransactions();if(!localTransactions.length)return cloudTransactions;const cloudIds=new Set(cloudTransactions.map(t=>t.id));const localOnly=localTransactions.filter(t=>t?.id&&!cloudIds.has(t.id));for(const transaction of localOnly)enqueuePendingSupabaseSync({type:'upsert_transaction',payload:transaction});return[...localOnly,...cloudTransactions]}
function mergeCards(cloudCards:FinancialCard[]):FinancialCard[]{const local=readLocalArray<FinancialCard>(CARDS_STORAGE_KEY);if(!local.length)return cloudCards;const cloudIds=new Set(cloudCards.map(c=>c.id));const localOnly=local.filter(c=>c?.id&&!cloudIds.has(c.id));return[...localOnly,...cloudCards]}
function mergeInstallmentPlans(cloudPlans:InstallmentPlan[]):InstallmentPlan[]{const local=readLocalArray<InstallmentPlan>(INSTALLMENTS_STORAGE_KEY);if(!local.length)return cloudPlans;const cloudIds=new Set(cloudPlans.map(p=>p.id));const localOnly=local.filter(p=>p?.id&&!cloudIds.has(p.id));return[...localOnly,...cloudPlans]}
export async function readUserDataFromSupabase(userId:string):Promise<SupabaseDataPayload>{if(!supabase)throw new Error('Supabase no está configurado.');const[transactionsResult,categoriesResult,budgetsResult,settingsResult,patrimonyResult,snapshotsResult,cardsResult,installmentPlansResult]=await Promise.all([supabase.from('calculator_transactions').select('*').eq('user_id',userId),supabase.from('calculator_categories').select('*').eq('user_id',userId),supabase.from('calculator_monthly_budgets').select('*').eq('user_id',userId),supabase.from('calculator_settings').select('*').eq('user_id',userId).maybeSingle(),supabase.from('calculator_assets').select('*').eq('user_id',userId).order('updated_at',{ascending:false}),supabase.from('calculator_net_worth_snapshots').select('*').eq('user_id',userId).order('snapshot_date',{ascending:false}),supabase.from('calculator_cards').select('*').eq('user_id',userId).order('created_at',{ascending:false}),supabase.from('calculator_installment_plans').select('*').eq('user_id',userId).order('created_at',{ascending:false})]);
if(transactionsResult.error)throw new Error(`Movimientos: ${transactionsResult.error.message}`);if(categoriesResult.error)throw new Error(`Categorías: ${categoriesResult.error.message}`);if(budgetsResult.error)throw new Error(`Presupuestos: ${budgetsResult.error.message}`);if(settingsResult.error)throw new Error(`Configuración: ${settingsResult.error.message}`);if(patrimonyResult.error)throw new Error(`Patrimonio: ${patrimonyResult.error.message}`);if(snapshotsResult.error)throw new Error(`Historial patrimonial: ${snapshotsResult.error.message}`);if(cardsResult.error)throw new Error(`Tarjetas: ${cardsResult.error.message}`);if(installmentPlansResult.error)throw new Error(`Planes de cuotas: ${installmentPlansResult.error.message}`);
const cloudTransactions=(transactionsResult.data??[]).map(row=>({id:row.id,title:row.title,amount:Number(row.amount),type:row.type,categoryId:row.category_id,date:row.date,paymentMethod:row.payment_method,notes:row.notes??undefined,isRecurring:row.is_recurring??false,cardId:row.card_id??undefined,installmentPlanId:row.installment_plan_id??undefined,installmentNumber:row.installment_number??undefined,installmentTotal:row.installment_total??undefined,installmentTotalAmount:row.installment_total_amount==null?undefined:Number(row.installment_total_amount),createdAt:row.created_at}));
return{transactions:mergeTransactions(cloudTransactions),categories:(categoriesResult.data??[]).map(row=>({id:row.id,name:row.name,icon:row.icon,color:row.color,textColor:row.text_color,type:row.type})),budgets:(budgetsResult.data??[]).map(row=>({monthKey:row.month_key,totalTarget:Number(row.total_target),categoryTargets:row.category_targets??{}})),settings:settingsResult.data?{currencySymbol:settingsResult.data.currency_symbol,currencyCode:settingsResult.data.currency_code,theme:settingsResult.data.theme,startDayOfMonth:settingsResult.data.start_day_of_month}:null,patrimonyItems:(patrimonyResult.data??[]).map(row=>({id:row.id,name:row.name,type:row.type,category:row.category,value:Number(row.value),valuationDate:row.valuation_date,notes:row.notes??undefined,createdAt:row.created_at,updatedAt:row.updated_at})),netWorthSnapshots:(snapshotsResult.data??[]).map(row=>({id:row.id,snapshotDate:row.snapshot_date,totalAssets:Number(row.total_assets),totalLiabilities:Number(row.total_liabilities),netWorth:Number(row.net_worth),createdAt:row.created_at})),cards:mergeCards((cardsResult.data??[]).map(row=>({id:row.id,name:row.name,type:row.type,brand:row.brand??undefined,last4:row.last4??undefined,creditLimit:row.credit_limit==null?undefined:Number(row.credit_limit),closingDay:row.closing_day??undefined,dueDay:row.due_day??undefined,active:row.active??true,createdAt:row.created_at}))),installmentPlans:mergeInstallmentPlans((installmentPlansResult.data??[]).map(row=>({id:row.id,cardId:row.card_id,title:row.title,totalAmount:Number(row.total_amount),installmentAmount:Number(row.installment_amount),installments:Number(row.installments),currentInstallment:Number(row.current_installment),startDate:row.start_date,transactionId:row.transaction_id??undefined,notes:row.notes??undefined,createdAt:row.created_at})))}};
